import type { Metadata } from "next";
import localFont from "next/font/local";

import { Providers } from "@/components/providers";

import "@/app/globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <link
                    href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Poppins:wght@400;700&family=Inter:wght@400;700&family=Lato:wght@400;700&family=Montserrat:wght@400;700&family=Nunito:wght@400;700&family=Source+Sans+Pro:wght@400;700&family=Merriweather:wght@400;700&family=Playfair+Display:wght@400;700&family=Space+Grotesk:wght@400;700&family=Raleway:wght@400;700&family=Oswald:wght@400;700&family=Open+Sans:wght@400;700&family=Cabin:wght@400;700&family=Muli:wght@400;700&family=Quicksand:wght@400;700&family=Lora:wght@400;700&family=Work+Sans:wght@400;700&family=Fira+Sans:wght@400;700&family=Bebas+Neue:wght@400;700&display=swap"
                        rel="stylesheet"
                />
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
